name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 16
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build JAR
        run: ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./app/build/libs/vektr.jar
